### ISSUE TITLE
【建议】读取配置文件两种方式拆开文档

### ISSUE THREAD

**Issue by liliang8858** [gogf/gf-doc#1]
https://goframe.org/os/gcfg/index

第一次使用
  上面 json读取方式  和 下面  toml 读取方式  很易混淆

【建议】读取配置文件两种方式拆开文档

**Comment by johngcn** [comment]
@liliang8858 简化了配置管理文档，修改了有歧义的语句，具体请查看 https://goframe.org/os/gcfg/index
