### ISSUE TITLE
`其他资料/准备工作 /Go Module.md` 的内容已过期

### ISSUE THREAD

**Issue by wufeng5702** [gogf/gf-doc#102]
https://github.com/gogf/gf-site/blob/5febe1252191ee6016bf6aa7f42e72446474f857/docs/docs/%E5%85%B6%E4%BB%96%E8%B5%84%E6%96%99/%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C/Go%20Module.md?plain=1#L31-L39

- `vgo` 已经被整合进 go 编译器内部了，不需要单独配置了。
- go get `gf@v1.6.13` 应该更新为 `gf@v2` 了，因为 `v1` 和 `v2` 差异很大。

**Comment by gqcn** [comment]
done
