### ISSUE TITLE
请教下中间件问题

### ISSUE THREAD

**Issue by Eric-chy** [gogf/gf-doc#37]
就是我在中间件里会查询下这个用户信息，可能不局限于用户用户信息，比如用户信息我可以session保存，在controller里可以通过session获取，但是如果是别的信息，我不太方便保存在session或者其他缓存里，我在controller里如何去复用这个已经查到数据呢？还有别人请求我接口的数据我在中间件里已经解析放到一个struct里了，在controller里需要重新再解析下吗？因为刚用这个不太熟悉，所以请教下

**Comment by gqcn** [comment]
@Eric-chy 你可以通过上下文变量：https://goframe.org/net/ghttp/request/context

**Comment by Eric-chy** [comment]
> @Eric-chy 你可以通过上下文变量：https://goframe.org/net/ghttp/request/context

感谢
