### ISSUE TITLE
GetQueriedSqls 是不是已经废弃了

### ISSUE THREAD

**Issue by botsphp** [gogf/gf-doc#40]
https://goframe.org/database/gdb/method#

代码中现在没有找到 `GetQueriedSqls`  的定义

**Comment by gqcn** [comment]
@botsphp 是的，新版本已去掉，这个方法其实在并发下统计并不准确，有需要的可以参考接口开发自行实现：https://goframe.org/database/gdb/interface/index

**Comment by botsphp** [comment]
好的。

PHP 框架里一般有获取上一条 SQL 的场景，比较有用。
