### ISSUE TITLE
更新记录

### ISSUE THREAD

**Issue by Q32611600** [gogf/gf-doc#60]
[https://goframe.org/dashboard.action#all-updates](https://wiki.goframe.org/dashboard.action#all-updates)  之前是这个地址
方便查看文档变动

**Comment by hailaz** [comment]
好像暂时没有好办法https://github.com/gogf/gf-site/commits/main/

**Comment by gqcn** [comment]
> 好像暂时没有好办法https://github.com/gogf/gf-site/commits/main/

感觉可以在ci中根据git log，只过滤*.md文件近期如7天的修改记录，自动生成一个markdown来展示。

**Comment by hailaz** [comment]
https://goframe.org/docs/changelog
